vich_uploader:
    db_driver: orm

    mappings:
        galerie_images:
            uri_prefix: '%app.path.galerie_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.galerie_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
